### ISSUE TITLE
twitter website was updated

### ISSUE THREAD

**Issue by fredcodee** [edoardottt/twitterBot#3]
the input tag for username and password was removed from the first page of twitter.com, now you have to click the login button to view the login page.

**Comment by edoardottt** [comment]
Thanks Bro, I saw that. Thanks anyway for your notification :)
I edit the twitterbot.py main file, where the login() function stays, I added a comment with some error fix. 
But I still see in my account the old version of Twitter Front End, so I decided to don't touch the code until Twitter definitely changes it. 
Thanks 👍

**Comment by edoardottt** [comment]
I close this issue because the twitter website seems returned to the old website front end. ALL WORKS NICELY.

**Comment by edoardottt** [comment]
The Twitter website changed another time.

**Comment by edoardottt** [comment]
I don't care anymore about this
